# test
name: develop

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:  # 各実行step
      - uses: actions/checkout@v2  # 使用するソースコード。repositoryからdownloadする
      - run: git status
      - run: git branch