name: Github Action with Rspec  # workflow name

on:  # トリガーとするイベントを定義
  push:  # repositoryにpush
    branches: [ main ]  # mainブランチが対象

jobs:  # 各jobを定義
  test:  # job name
    runs-on: ubuntu-latest  # jobを実行する環境を指定
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1

    services:
      mysql:  # service name
        image: mysql:8.0  # 使いたいimageを指定
        env:  # 環境変数を定義
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        # ports:  # 使うportを指定。ポートフォワードできる
        #   - 3306

    steps:  # 各実行step
      - uses: actions/checkout@v2  # 使用するソースコード。repositoryからdownloadする
      - name: Setup Ruby 3.0  # step name
        uses: ruby/setup-ruby@v1  # # 使用するソースコード。repositoryからdownloadする
        with:  # 付属情報
          ruby-version: 3.0

      - name: setup MySQL
        run: |
          sudo apt update
          sudo apt install mysql-client
          sudo apt install libmysqlclient-dev

      - name: Install bundler  # step name
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      
      - name: Check yarn
        run: |
          yarn install --check-files
      
      - name: Migration
        run: |
          bundle exec rails db:create

  # - name: Run tests  # step name
  #   run: bundle exec rspec

  # - uses: actions/checkout@v2
  # - uses: actions/setup-node@v1
  # - run: npm install -g bats
  # - run: bats -v
  # Run Rspec # このjobの名前
  #   runs-on: ubuntu-latest  # このjobを実行するコンテナ
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Ruby 3.0
  #       uses: action/setup-ruby@v1
  #       with:
  #         ruby-version: 3.0.2
  #     - name: Test with Rspec
  #       run: |
  #         gem install bundler
  #         bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
  #         bundle exec rspec

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
    #     with:
    #       heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #       heroku_app_name: "thawing-reaches-18664"
    #       heroku_email: "q8tpk5yaqkutovncyabe@gmail.com"
