name: Github Action with Rspec  # workflow name

on:  # トリガーとするイベントを定義
  push:  # repositoryにpush
    branches: [ main ]  # mainブランチが対象

jobs:  # jobを定義
  test:  # job name
    runs-on: ubuntu-latest  # jobを実行する環境を指定
    steps:  # 各実行step
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake

      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      # - run: npm install -g bats
      # - run: bats -v
  # Run Rspec # このjobの名前
  #   runs-on: ubuntu-latest  # このjobを実行するコンテナ
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Ruby 3.0
  #       uses: action/setup-ruby@v1
  #       with:
  #         ruby-version: 3.0.2
  #     - name: Test with Rspec
  #       run: |
  #         gem install bundler
  #         bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
  #         bundle exec rspec

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
    #     with:
    #       heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #       heroku_app_name: "thawing-reaches-18664"
    #       heroku_email: "q8tpk5yaqkutovncyabe@gmail.com"
