name: Github Action with Rspec  # workflow name

on:  # トリガーにするイベントを定義
  push:  # repositoryにpush
    branches: [ main ]  # mainブランチが対象

jobs:  # jobを定義していく
  init:  # job name
    runs-on: ubuntu-latest  # jobを実行するホストを指定
    env: # 環境変数を定義
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    # コンテナを使いたい時はこれを定義する
    services:
      mysql:  # コンテナ名
        image: mysql:8.0.23  # 使いたいimageを指定
        # volumes:  # コンテナにmountしたいファイルを定義
        #   - mysqlconf.d:/etc/mysql/conf.d
        env:  # 環境変数を定義
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND_ADDRESS: 0.0.0.0
        ports:  # 使うportを指定。ポートフォワードできる
          - 3306:3306

    steps:  # 各実行step
      - uses: actions/checkout@v2  # 使用するソースコード。repositoryからdownloadする
      - name: Setup Ruby 3.0  # step name
        uses: ruby/setup-ruby@v1  # # 使用するソースコード。repositoryからdownloadする
        with:  # 付属情報
          ruby-version: 3.0
          bundler-cache: true

      - name: Install bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      
      - name: Check yarn
        run: |
          yarn install
          yarn install --check-files
      
      - name: Migration
        run: |
          bundle exec rails db:create
      
      - name: Run rspec
        run: bundle exec rspec