name: Slack Notification

on:
  push:
    branches: [develop]

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW: ${{ GITHUB_WORKFLOW }}
    steps:
        - uses: actions/checkout@v2
        - run: |
            echo "The FOO is ${GITHUB_WORKFLOW}"