name: Slack Notification

on:
  push:
    branches: [develop]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: |
            curl -X POST \
                 -H "Content-type: application/json; charset=utf-8" \
                 -d '{
                        "attachments": [
                          {
                            "color": "#2dde16",
                            "blocks": [
                              {
                                "type": "sections",
                                  "text": {
                                    "type": "mrkdwn",
                                    "text": "${{ github.workflow }} ${{ job.status }}"
                                  }
                              },
                              {
                                "type": "section",
                                "text": {
                                  "type": "mrkdwn",
                                  "text": "${{ github.actor }}"
                                }
                              }
                            ]
                          }
                        ]
                      }' \
                    ${{ secrets.SLACK_WEBHOOK_URL }}