name: Slack Notification

on:
  push:
    branches: [develop]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: |
            FOO= ${{ GITHUB_JOB }}
            echo "The FOO is ${FOO}"