name: Slack Notification

on:
  push:
    branches: [develop]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        # - run: echo "Author name ${{ github.actor }}"
        # - run: echo "Repository URL ${{ github.event.repository.url }}"
        # - run: echo "GitHub Actions URL ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
        - run: |
            curl -X POST \
                 -H "Content-type: application/json; charset=utf-8" \
                 -d '{"blocks": [ 
                   {
                     "type": "section",
                     "text": {
                       "type": "mrkdwn",
                       "text": "New Paid Time Off request from <example.com|Fred Enriquez>\n\n<https://example.com|View request>"
                     }
                   }
                 ] }' \
                 ${{ secrets.SLACK_WEBHOOK_URL }}